### ISSUE TITLE
Player ID not parsed correctly in `cfbd_json_py.players.get_cfbd_player_season_stats()`

### ISSUE THREAD

**Issue by erikhall6373** [armstjc/cfbd-json-py#51]
Hi I've been recently using this package for a Heisman trophy model, and have found it a lot more accessible than the regular cfbd package.

Caught a bug I believe in the code for the get_cfbd_player_season_stats function.

For passing statistics player_id appropriately commented out,

![image](https://github.com/user-attachments/assets/8a54196f-76e4-4940-873f-3085afe043b9)

But not for rushing statistics,

![image](https://github.com/user-attachments/assets/fbcaf068-562a-4bb6-aac7-29c78ae36451)

I personally like having player_id available, and I was playing around with the code to get it to work.

I figured this kind of patch would work for the function,

![image](https://github.com/user-attachments/assets/ad873a3e-dee1-4163-bbab-37dc03588cb6)

Thanks for all that you do in this package!

**Comment by armstjc** [comment]
Issue has been identified, update will be pushed as soon as I can validate that the fix has been implemented corectly.

Thanks for the bug find!
